import streamlit as st
import pandas as pd
import joblib
import numpy as np

# ================= Configuration =================
st.set_page_config(
    page_title="脑卒中后风险预测",
    page_icon="🏥",
    layout="centered"
)

# Custom CSS for medical-grade styling
st.markdown("""
    <style>
    .main {background-color: #f8f9fa;}
    .stButton>button {
        width: 100%;
        background-color: #007bff;
        color: white;
        font-size: 18px;
        font-weight: bold;
        padding: 12px;
        border-radius: 8px;
        border: none;
    }
    .stButton>button:hover {
        background-color: #0056b3;
    }
    .result-card {
        padding: 25px;
        border-radius: 12px;
        box-shadow: 0 4px 15px rgba(0,0,0,0.1);
        text-align: center;
        margin-top: 25px;
        font-family: 'Arial', sans-serif;
    }
    .input-label {
        font-weight: 600;
        font-size: 14px;
    }
    </style>
""", unsafe_allow_html=True)

# ================= Header =================
st.title("🏥 脑卒中后风险预测")
st.markdown("""
    本工具基于 **Logistic Regression**模型用于预测脑卒中患者的**SAP**发病风险。
""")
st.markdown("---")


# ================= Load Model =================
@st.cache_resource
def load_model_data():
    try:
        # Load the file generated by your training script
        return joblib.load('web_app_data.pkl')
    except FileNotFoundError:
        return None


data = load_model_data()

if data is None:
    st.error("⚠️ Model file ('web_app_data.pkl') not found. Please run your training script first to generate it.")
    st.stop()

model = data['model']
# We expect the 'features' list in the pickle file to match your 11 variables,
# but we define the explicit input order here for the UI.
required_features = [
    'age', 'BMI', 'MAC', 'DD', 'PTr',
    'neutrophil', 'Np', 'LYMp', 'globulin', 'Hb', 'Ca'
]

# ================= Input Form =================
with st.form("prediction_form"):
    # --- Section 1: Demographics & Vitals ---
    st.subheader("👤 基本情况")
    col1, col2 = st.columns(2)

    with col1:
        age = st.number_input("年龄：Age (years)", min_value=18, max_value=120, value=65, step=1)
        bmi = st.number_input("BMI (kg/m²)", min_value=10.0, max_value=60.0, value=24.0, format="%.1f")

    with col2:
        # Mean Corpuscular Hemoglobin Concentration
        mac = st.number_input("平上臂中点周长:MAC (cm)", min_value=10.0, max_value=100.0, value=330.0, format="%.1f")

    st.markdown("")  # Spacing

    # --- Section 2: Blood & Coagulation Markers ---
    st.subheader("🩸 血常规指标")
    col3, col4, col5 = st.columns(3)

    with col3:
        # D-dimer
        dd = st.number_input("D二聚体：D-dimer (DD) (mg/L)", min_value=0.0, max_value=150.0, value=0.5, format="%.2f")
        # Prothrombin Time Ratio
        ptr = st.number_input("凝血酶原时间比值：PTr (Ratio)", min_value=0.5, max_value=5.0, value=1.0, format="%.2f")

    with col4:
        # Neutrophil Count
        neutrophil = st.number_input("中性粒细胞计数：Neutrophil Count (10⁹/L)", min_value=0.0, max_value=50.0, value=4.0,
                                     format="%.2f")
        # Neutrophil Percentage
        np_val = st.number_input("中性粒细胞百分比：Neutrophil % (Np)", min_value=0.0, max_value=100.0, value=60.0, format="%.1f")

    with col5:
        # Lymphocyte Percentage
        lymp = st.number_input("淋巴细胞百分比：Lymphocyte % (LYMp)", min_value=0.0, max_value=100.0, value=30.0, format="%.1f")

    st.markdown("")  # Spacing

    # --- Section 3: Biochemistry ---
    st.subheader("🧪 血生化指标")
    col6, col7, col8 = st.columns(3)

    with col6:
        globulin = st.number_input("球蛋白：Globulin (g/L)", min_value=10.0, max_value=100.0, value=25.0, format="%.1f")
    with col7:
        hb = st.number_input("血红蛋白：Hemoglobin (Hb) (g/L)", min_value=50, max_value=250.0, value=130.0, format="%.1f")
    with col8:
        ca = st.number_input("钙：Calcium (Ca) (mmol/L)", min_value=1.0, max_value=5.0, value=2.25, format="%.2f")

    # ================= Prediction Logic =================
    submitted = st.form_submit_button("🚀 Calculate Risk")

if submitted:
    # 1. Collect inputs into a dictionary
    # keys must match EXACTLY with the feature names trained in the model
    input_data = {
        'age': age,
        'BMI': bmi,
        'MAC': mac,
        'DD': dd,
        'PTr': ptr,
        'neutrophil': neutrophil,
        'Np': np_val,
        'LYMp': lymp,
        'globulin': globulin,
        'Hb': hb,
        'Ca': ca
    }

    # 2. Convert to DataFrame (ensures correct column names)
    input_df = pd.DataFrame([input_data])

    # 3. Ensure column order matches the trained model exactly
    # (If your pipeline uses a column transformer, this is critical)
    try:
        input_df = input_df[required_features]
    except KeyError as e:
        st.error(f"Error: Model expects feature {e}, but it was not provided.")
        st.stop()

    # 4. Make Prediction
    try:
        # Predict Probability (index 1 is the positive class 'SAP')
        probability = model.predict_proba(input_df)[0][1]

        # Determine Risk Level
        risk_percentage = probability * 100

        st.markdown("---")

        # Display Result Card
        if probability > 0.5:
            st.markdown(f"""
                <div class="result-card" style="background-color: #ffebee; border: 2px solid #ef5350;">
                    <h2 style="color: #c62828;">⚠️ High Risk Detected</h2>
                    <h1 style="font-size: 50px; color: #c62828; margin: 10px 0;">{risk_percentage:.1f}%</h1>
                    <p style="font-size: 18px; color: #b71c1c;">
                        The model suggests this patient is at <b>HIGH risk</b> for Severe Acute Pancreatitis.
                    </p>
                </div>
            """, unsafe_allow_html=True)
        else:
            st.markdown(f"""
                <div class="result-card" style="background-color: #e8f5e9; border: 2px solid #66bb6a;">
                    <h2 style="color: #2e7d32;">✅ Low Risk</h2>
                    <h1 style="font-size: 50px; color: #2e7d32; margin: 10px 0;">{risk_percentage:.1f}%</h1>
                    <p style="font-size: 18px; color: #1b5e20;">
                        The model suggests this patient is at <b>LOW risk</b> for Severe Acute Pancreatitis.
                    </p>
                </div>
            """, unsafe_allow_html=True)

        # 5. Interpretation / Visual Guide
        st.write("")
        st.write("### 疾病风险水平")
        st.progress(int(risk_percentage))
        st.caption("0% = No Risk | 100% = Certainty")

    except Exception as e:
        st.error(f"An error occurred during prediction: {str(e)}")